version: "3.8"

services:
  web:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./php/www:/var/www/html
    links:
      - db
    restart: unless-stopped

  db:
    build: ./db
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: user
      MYSQL_USER: password
      MYSQL_PASSWORD: appDB
    restart: unless-stopped
