version: "3.8"

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - "3308:3306"
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/content:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    links:
      - db
  apache:
    build: ./apache
    restart: unless-stopped
    volumes:
      - ./apache/content:/var/www/html/
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8081:80"
    links:
      - db
      - nginx
